# Generated by Django 5.1.2 on 2024-10-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='date_guessed',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='guess',
            name='feedback',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='guess',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_text',
            field=models.CharField(max_length=5),
        ),
    ]
